name: 'Github CD Action'
description: 'The deploy to k8s as a GitHub Action'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.version }} ${{ inputs.command }} ${{ inputs.binaries-url }}
      shell: bash
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: 'kubectl version, e.g. `v1.21.0`, defaults to latest'
    required: false
    default: latest
  command:
    description: 'kubectl command to run, without the kubectl, e.g. `get pods`'
    required: true
  binaries-url:
    description: 'Url to download the binaries from, defaults to the official dl.k8s.io url' 
    required: false
